---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  {{- if .Values.hooks.enabled }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded
  {{- end }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: pg-dba
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        pullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.postgres.host }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.pass }}
        - name: SSL_MODE
          value: {{ .Values.postgres.sslMode }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
